#!/bin/sh

# Validation.
if [ ! $APPINSIGHTS_CONNECTIONSTRING ];
then
    echo "Warning: Application Insights is not setup.  Application will log to console."
fi

# Run app.
exec env APPINSIGHTS_CONNECTIONSTRING=$(cat $APPINSIGHTS_CONNECTIONSTRING) env ATLAS_CLUSTER_URL=$(cat $ATLAS_CLUSTER_URL_FILE) env DISCORD_CLIENTID=$(cat $DISCORD_CLIENTID_FILE) env DISCORD_CLIENTSECRET=$(cat $DISCORD_CLIENTSECRET_FILE) env DISCORD_TOKEN=$(cat $DISCORD_TOKEN_FILE) env ENCRYPTION_KEY=$(cat $ENCRYPTION_KEY_FILE) env REDIS_PASSWORD=$(cat $REDIS_PASSWORD_FILE) env TWITCH_BOT_ACCESSTOKEN=$(cat $TWITCH_BOT_ACCESSTOKEN_FILE) env TWITCH_BOT_REFRESHTOKEN=$(cat $TWITCH_BOT_REFRESHTOKEN_FILE) env TWITCH_CHANNEL_ACCESSTOKEN=$(cat $TWITCH_CHANNEL_ACCESSTOKEN_FILE) env TWITCH_CHANNEL_EVENTSUB_SECRET=$(cat $TWITCH_CHANNEL_EVENTSUB_SECRET_FILE) env TWITCH_CHANNEL_REFRESHTOKEN=$(cat $TWITCH_CHANNEL_REFRESHTOKEN_FILE) env TWITCH_CLIENTID=$(cat $TWITCH_CLIENTID_FILE) env TWITCH_CLIENTSECRET=$(cat $TWITCH_CLIENTSECRET_FILE) env WEB_SIXGG_PASSWORD=$(cat $WEB_SIXGG_PASSWORD_FILE) node index
