name: Dependabot automerge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{github.actor == 'dependabot[bot]'}}
    steps:
      - name: Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
      - name: Automerge
        if: ${{contains(steps.metadata.outputs.dependency-names, '@babel/') || contains(steps.metadata.outputs.dependency-names, '@types/') || steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
